"""Builds one C source file containing both the pre-fix and post-fix
versions of a function (renamed to avoid a symbol clash), plus a small
main() that: given a truncation length L on the command line, builds a
heap buffer of EXACTLY L+1 bytes (no slack past the string, so ASan can
catch a read past it) holding the first L bytes of a caller-supplied
seed string, and calls whichever implementation ("old"/"new") was
requested with that buffer as the tainted string parameter.

Deliberately narrow: this only knows how to wire up a function with
exactly one string-like parameter (the one the UnboundedCopyFinding's
taint traced through) and any number of plain integer parameters, which
are filled with caller-supplied literal defaults, not synthesized."""
from __future__ import annotations

from ..pattern.function_extractor import ExtractedFunction
from ..pattern.signature import Parameter
from ..pattern.unbounded_copy import UnboundedCopyFinding


class UnsupportedSignatureError(ValueError):
    pass


class DifferentialHarnessGenerator:
    def generate(
        self,
        old_fn: ExtractedFunction,
        new_fn: ExtractedFunction,
        finding: UnboundedCopyFinding,
        seed: str,
        other_param_defaults: dict[str, str],
    ) -> str:
        if old_fn.signature is None or not old_fn.signature.is_simple():
            raise UnsupportedSignatureError(f"{old_fn.name}'s signature is not a supported simple shape")

        string_params = [p for p in old_fn.signature.parameters if p.is_string_like()]
        if len(string_params) != 1:
            raise UnsupportedSignatureError("harness generation needs exactly one string-like parameter")
        string_param = string_params[0]

        missing = [
            p.name for p in old_fn.signature.parameters
            if p is not string_param and p.name not in other_param_defaults
        ]
        if missing:
            raise UnsupportedSignatureError(f"missing default value(s) for parameter(s): {', '.join(missing)}")

        old_renamed = self._rename_function(old_fn, f"old_{old_fn.name}")
        new_renamed = self._rename_function(new_fn, f"new_{new_fn.name}")

        call_args_old = self._build_call_args(old_fn.signature.parameters, string_param, other_param_defaults)
        call_args_new = self._build_call_args(new_fn.signature.parameters, string_param, other_param_defaults)

        escaped_seed = self._escape_c_string(seed)

        return f'''/* Auto-generated by Augur -- differential ASan harness.
 * Target function: {old_fn.name}
 * Detected pattern: fixed-size memcpy into `{finding.dest_buffer}`
 *   ({finding.dest_size} bytes) from `{finding.source_expr}`, which
 *   traces back to the string-like parameter `{string_param.name}`.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char SEED[] = "{escaped_seed}";

/* ---- old implementation ---- */
{old_renamed}

/* ---- new implementation ---- */
{new_renamed}

int main(int argc, char **argv) {{
    if (argc != 3) {{
        fprintf(stderr, "usage: %s <old|new> <truncate_length>\\n", argv[0]);
        return 2;
    }}
    const char *which = argv[1];
    long trunc_len = strtol(argv[2], NULL, 10);
    long seed_len = (long)strlen(SEED);
    if (trunc_len < 0 || trunc_len > seed_len) trunc_len = seed_len;

    /* Heap-allocate exactly trunc_len+1 bytes -- no slack past the
     * string's real end, so ASan flags any read beyond it. */
    char *buf = (char *)malloc((size_t)trunc_len + 1);
    if (!buf) return 3;
    memcpy(buf, SEED, (size_t)trunc_len);
    buf[trunc_len] = '\\0';

    if (strcmp(which, "old") == 0) {{
        old_{old_fn.name}({call_args_old});
    }} else {{
        new_{new_fn.name}({call_args_new});
    }}

    free(buf);
    return 0;
}}
'''

    @staticmethod
    def _rename_function(fn: ExtractedFunction, new_name: str) -> str:
        # The function name's first occurrence in the extracted text is
        # always the declaration itself (extraction starts at the
        # signature match), so replacing only the first occurrence can't
        # accidentally rename an unrelated identical identifier elsewhere
        # in the body.
        return fn.full_text.replace(fn.name, new_name, 1)

    @staticmethod
    def _escape_c_string(text: str) -> str:
        """Escapes a Python string into a C string-literal body. Each
        escape sequence still compiles down to exactly one byte, so
        len(original_text) continues to equal strlen(SEED) at runtime --
        the truncation-length arithmetic in the generated harness depends
        on that equivalence holding."""
        out = []
        for ch in text:
            code = ord(ch)
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\t":
                out.append("\\t")
            elif 32 <= code < 127:
                out.append(ch)
            else:
                # C hex escapes greedily consume every following hex-digit
                # character, so a literal character right after \xNN that
                # happens to look like a hex digit would silently merge
                # into the escape. `""` immediately after closes the
                # literal and reopens it, which C concatenates back
                # together at compile time -- a hard boundary the escape
                # can't read past.
                out.append(f'\\x{code:02x}""')
        return "".join(out)

    @staticmethod
    def _build_call_args(parameters: list[Parameter], string_param: Parameter, defaults: dict[str, str]) -> str:
        # Compared by name, not identity: old_fn's and new_fn's parameter
        # lists are parsed separately, so they're always distinct Parameter
        # instances even when they represent the same logical argument.
        args = []
        for p in parameters:
            args.append("buf" if p.name == string_param.name else defaults[p.name])
        return ", ".join(args)
