"""Builds one C source file containing both the pre-fix and post-fix
versions of a function (renamed to avoid a symbol clash), plus a small
main() that: given a truncation length L on the command line, builds a
heap buffer of EXACTLY L+1 bytes (no slack past the string, so ASan can
catch a read past it) holding the first L bytes of a caller-supplied
seed string, and calls whichever implementation ("old"/"new") was
requested with that buffer as the tainted string parameter.

Deliberately narrow: this only knows how to wire up a function with
exactly one string-like parameter (the one the UnboundedCopyFinding's
taint traced through) and any number of plain integer parameters, which
are filled with caller-supplied literal defaults, not synthesized."""
from __future__ import annotations

import re

from ..pattern.function_extractor import ExtractedFunction
from ..pattern.signature import Parameter
from ..pattern.unbounded_copy import UnboundedCopyFinding


class UnsupportedSignatureError(ValueError):
    pass


class DifferentialHarnessGenerator:
    def generate(
        self,
        old_fn: ExtractedFunction,
        new_fn: ExtractedFunction,
        finding: UnboundedCopyFinding,
        seed: str,
        other_param_defaults: dict[str, str],
    ) -> str:
        if old_fn.signature is None or not old_fn.signature.is_simple():
            raise UnsupportedSignatureError(f"{old_fn.name}'s signature is not a supported simple shape")
        if new_fn.signature is None or not new_fn.signature.is_simple():
            raise UnsupportedSignatureError("the new function's signature is not a supported simple shape")
        old_params = old_fn.signature.parameters
        new_params = new_fn.signature.parameters
        if len(old_params) != len(new_params) or any(
            a.pointer_depth != b.pointer_depth or a.type_tokens != b.type_tokens
            for a, b in zip(old_params, new_params)
        ):
            raise UnsupportedSignatureError("parameter types or positions changed between versions")
        if "\0" in seed:
            raise UnsupportedSignatureError("seed contains NUL; only NUL-free UTF-8 strings are supported")

        string_params = [p for p in old_fn.signature.parameters if p.is_string_like()]
        if len(string_params) != 1:
            raise UnsupportedSignatureError("harness generation needs exactly one string-like parameter")
        string_param = string_params[0]

        missing = [
            p.name for p in old_fn.signature.parameters
            if p is not string_param and p.name not in other_param_defaults
        ]
        if missing:
            raise UnsupportedSignatureError(f"missing default value(s) for parameter(s): {', '.join(missing)}")

        old_renamed = self._rename_function(old_fn, f"old_{old_fn.name}")
        new_renamed = self._rename_function(new_fn, f"new_{new_fn.name}")

        call_args_old = self._build_call_args(old_fn.signature.parameters, string_param, other_param_defaults)
        # Argument positions retain their meaning even if parameter names change.
        call_args_new = call_args_old

        escaped_seed = self._escape_c_string(seed)

        return f'''/* Auto-generated by Augur -- differential ASan harness.
 * Target function: {old_fn.name}
 * Detected pattern: fixed-size memcpy into `{finding.dest_buffer}`
 *   ({finding.dest_size} bytes) from `{finding.source_expr}`, which
 *   traces back to the string-like parameter `{string_param.name}`.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

static const char SEED[] = "{escaped_seed}";

/* ---- old implementation ---- */
{old_renamed}

/* ---- new implementation ---- */
{new_renamed}

int main(int argc, char **argv) {{
    if (argc != 3) {{
        fprintf(stderr, "usage: %s <old|new> <truncate_length>\\n", argv[0]);
        return 2;
    }}
    const char *which = argv[1];
    long trunc_len = strtol(argv[2], NULL, 10);
    long seed_len = (long)(sizeof(SEED) - 1);
    if (trunc_len < 0 || trunc_len > seed_len) trunc_len = seed_len;

    /* Heap-allocate exactly trunc_len+1 bytes -- no slack past the
     * string's real end, so ASan flags any read beyond it. */
    char *buf = (char *)malloc((size_t)trunc_len + 1);
    if (!buf) return 3;
    memcpy(buf, SEED, (size_t)trunc_len);
    buf[trunc_len] = '\\0';

    if (strcmp(which, "old") == 0) {{
        old_{old_fn.name}({call_args_old});
    }} else {{
        new_{new_fn.name}({call_args_new});
    }}

    free(buf);
    return 0;
}}
'''

    @staticmethod
    def _rename_function(fn: ExtractedFunction, new_name: str) -> str:
        # Match the declaration token, not a substring of its return type.
        return re.sub(rf"\b{re.escape(fn.name)}(?=\s*\()", new_name, fn.full_text, count=1)

    @staticmethod
    def _escape_c_string(text: str) -> str:
        """Encode UTF-8 bytes using fixed-width C octal escapes.

        Fixed width prevents adjacent digits from extending an escape, and
        encoding bytes rather than code points preserves Unicode input.
        """
        out = []
        for code in text.encode("utf-8"):
            ch = chr(code)
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\t":
                out.append("\\t")
            elif 32 <= code < 127:
                out.append(ch)
            else:
                out.append(f"\\{code:03o}")
        return "".join(out)

    @staticmethod
    def _build_call_args(parameters: list[Parameter], string_param: Parameter, defaults: dict[str, str]) -> str:
        # Compared by name, not identity: old_fn's and new_fn's parameter
        # lists are parsed separately, so they're always distinct Parameter
        # instances even when they represent the same logical argument.
        args = []
        for p in parameters:
            args.append("buf" if p.name == string_param.name else defaults[p.name])
        return ", ".join(args)
